name = "ModularSchur"
defaultTargets = ["ModularSchur"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8f9d9cff6bd728b17a24e163c9402775d9e6a365"

[[lean_lib]]
name = "ModularSchur"
